---
# Credentials that will be used as an Admin account for our deployed our Ops Manager
apiVersion: v1
data:
  FirstName: QWRtaW4=
  LastName: QWRtaW4=
  Password: UGFzc3cwcmQxIQo=    # Passw0rd1!
  Username: YWRtaW4=            # admin
kind: Secret
metadata:
  name: om-admin-credentials
  namespace: mongodb
type: Opaque
...
---
# Create an Ops Manager (and application database) that we can use for future deployments
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: opsman
  namespace: mongodb

# We need approx 6GB per Ops Manager / Backup Daemon, so running 1 replica
spec:
  replicas: 1
  version: 4.2.22
  adminCredentials: om-admin-credentials

  # This will prevent us having to go through the setup wizad when we first connect to Ops Manager
  configuration:
    mms.ignoreInitialUiSetup: "true"
    automation.versions.source: mongodb
    mms.adminEmailAddr: no@email.com
    mms.fromEmailAddr: om@email.com
    mms.mail.hostname: localhost
    mms.mail.port: "25"
    mms.mail.ssl: "false"
    mms.mail.transport: smtp
    mms.minimumTLSVersion: TLSv1.2
    mms.replyToEmailAddr: no@email.com

  # We will want to access the Ops Manager UI from outside K8s so lets get a port in the 30000-32767 range for that
  externalConnectivity:
    type: NodePort
    port: 30100 

  # Application Database settings, trying to use minimal resources
  applicationDatabase:
    members: 3
    version: 4.2.11-ent
    podSpec:
      cpu: '0.25'
      memory: 350M
      persistence:
        single:
          storage: 1G

  # Backup settings, false for now as we will need to setup an oplog/blockstore before we enable it
  backup:
    enabled: false
...
